spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST}/${DB_NAME}?useSSL=false
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
#    url: jdbc:mysql://192.168.59.100:3306/javatechie?useSSL=false
#    username: root
#    password: root
    hikari:
      initialization-fail-timeout: 0
#  jpa:
#    database-platform: org.hibernate.dialect.MySQLDialect
#    generate-ddl: true
#    show-sql: true
#    hibernate:
#      ddl-auto: update